# Feature configuration for response attribution system

# Confidence weights for different factors
confidence_weights:
  base: 0.3
  consistency: 0.3
  causality: 0.3
  temporal: 0.3
  effect: 0.4
  uncertainty_penalty: 0.2
  side_effect_boost: 0.1
  cluster_size: 0.2
  dimension: 1.0

# Causal confidence weights
causal_confidence_weights:
  base: 0.3  # Base confidence from dependency distance
  pattern: 0.3  # Confidence from causal patterns
  temporal: 0.2  # Confidence from temporal ordering
  event: 0.2  # Confidence from event ordering

# Weights for different response dimensions
dimension_weights:
  activation: 1.0
  emotional: 1.0
  metabolic: 1.0

# Confidence thresholds
confidence_thresholds:
  floor: 0.2
  ceiling: 0.95
  min_signal: 0.15

# Proximity settings
proximity:
  decay_factor: 0.8
  max_distance: 10

# Cross-sentence settings
cross_sentence:
  window_size: 2  # Number of sentences to look before/after
  decay_factor: 0.7  # Decay factor for cross-sentence evidence
  min_confidence: 0.3  # Minimum confidence for cross-sentence evidence
  max_distance: 5  # Maximum token distance for cross-sentence evidence

# Temporal recency weights
temporal_recency_weights:
  current: 1.0    # Within a week
  recent: 0.8     # Within a month
  past: 0.5       # Within 6 months
  distant: 0.2    # More than 6 months

# Coreference settings
coreference:
  enabled: true
  max_distance: 5  # Maximum distance for coreference resolution
  min_confidence: 0.6  # Minimum confidence for coreference resolution
  pronouns:  # Pronouns to track
    - "it"
    - "this"
    - "that"
    - "they"
    - "them"
    - "these"
    - "those"
    - "its"
    - "itself"
    - "one"
    - "ones"
    - "which"
    - "who"
    - "whom"
    - "whose"
  medication_specific:
    enabled: true
    min_confidence: 0.7  # Higher confidence threshold for medication coreference
    max_distance: 3  # Shorter distance for medication coreference
    context_window: 2  # Number of sentences to look before/after for medication context
  logging:
    level: "DEBUG"
    track_resolutions: true
    track_confidence: true

# Uncertainty estimation weights
uncertainty_weights:
  epistemic: 0.6
  aleatoric: 0.4

# Cache settings
cache:
  causality_cache_size: 10000
  fuzzy_cache_size: 5000
  temporal_cache_size: 5000
  emoji_cache_size: 1000
  compression_threshold: 1024  # 1KB
  warmup_size: 100
  eviction_policy: "lru_freq"
  track_stats: true
  compression_enabled: true
  warmup_enabled: true

# Word2Vec settings
word2vec:
  enabled: false
  model_path: "data/models/word2vec-google-news-300.bin"  # Optional path to pre-downloaded model
  version: "1.0"  # Lock to specific version
  memory_map: true  # Use memory mapping for large models

# Symptom matcher configuration
symptom_matcher:
  lexicon_path: "data/lexicons/symptom_lexicon.yaml"
  fuzzy_threshold: 0.85
  max_fuzzy_terms: 1000
  cache:
    fuzzy_cache_size: 5000

# Temporal parser configuration
temporal_parser:
  max_distance: 10
  decay_factor: 0.8
  temporal_patterns:
    - pattern: "started taking"
      weight: 0.9
    - pattern: "stopped taking"
      weight: 0.9
    - pattern: "been on"
      weight: 0.8
    - pattern: "tried"
      weight: 0.7

# Emoji processor configuration
emoji_processor:
  max_distance: 5
  decay_factor: 0.9
  emoji_categories:
    activation:
      - "😴"  # Sleepy
      - "😫"  # Tired
      - "😤"  # Energetic
    emotional:
      - "😊"  # Happy
      - "😢"  # Sad
      - "😡"  # Angry
    metabolic:
      - "😋"  # Hungry
      - "🤢"  # Nauseous
      - "😴"  # Sleepy

# Causal pattern configuration
causal_patterns:
  direct:
    - pattern: "makes me feel"
      weight: 0.9
    - pattern: "causes me to"
      weight: 0.9
    - pattern: "results in"
      weight: 0.8
  indirect:
    - pattern: "seems to help with"
      weight: 0.7
    - pattern: "appears to reduce"
      weight: 0.7
    - pattern: "might be helping"
      weight: 0.6

# Debug settings
debug:
  log_level: "INFO"
  detailed_confidence: false
  cache_stats: false

logging:
  log_dir: "logs"
  module_levels:
    features.symptom_matcher: INFO
    features.response_attribution: INFO
    features.temporal_parser: INFO
    features.emoji_processor: INFO
    models.confidence_aware_training: INFO
    models.main_pipeline: INFO
    evaluation.evaluate_confidence: INFO 